' Gambas module file

Public Sub main()

  Dim ruta As String
  Dim soloruta As String

  Try ruta = Clipboard.Paste("text/plain")
  If Error Then
    Exec "caja"
  Else
    ruta = Replace(ruta, "\n", "")
    If IsDir(ruta) Then
      Exec ["caja", ruta]
    Else
      If RInStr(ruta, "/") > 0 Then
        soloruta = Mid$(ruta, 1, RInStr(ruta, "/") - 1)
        If IsDir(soloruta) Then

          Exec ["caja", soloruta]
        Else
          Exec ["caja"]
        Endif

      Endif

      Exec ["caja"]
    Endif

  Endif
  Quit

End
